apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: k8s-gsm-tools
  name: k8s-gsm-tools
  annotations: 
    iam.gke.io/gcp-service-account: k8s-gsm-tools@spiffxp-gke-dev.iam.gserviceaccount.com  
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-gsm-tools
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-gsm-tools
subjects:
- kind: ServiceAccount
  namespace: k8s-gsm-tools
  name: k8s-gsm-tools
roleRef:
  kind: ClusterRole
  name: k8s-gsm-tools
  apiGroup: rbac.authorization.k8s.io