presubmits:
  bashfire/prow-config:
  - name: pull-prow-config-checkconfig
    cluster: prow-build-test
    decorate: true
    run_if_changed: '^(config/prow/(config|plugins).yaml$|config/jobs/.*.yaml$)'
    optional: true
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20200423-af610499d
        command:
        - /checkconfig
        args:
        - --config-path=config/prow/config.yaml
        - --plugin-config=config/prow/plugins.yaml
        - --strict
        - --warnings=mismatched-tide-lenient
        - --warnings=tide-strict-branch
        - --warnings=needs-ok-to-test
        - --warnings=validate-owners
        - --warnings=missing-trigger
        - --warnings=validate-urls
        - --warnings=unknown-fields
  - name: pull-prow-dind-experiment
    cluster: prow-build-test
    decorate: true
    always_run: false
    optional: true
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:latest-master
        command:
        - /bin/bash
        args:
        - -c
        - docker system info


periodics:
- interval: 5m
  cluster: prow-build-test
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]

postsubmits:
  bashfire/prow-config:
  - name: post-prow-config
    cluster: prow-build-test
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
